apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpechave-deployment
  labels:
    app: bpechave
spec:
  selector:
    matchLabels:
      app: bpechave
  template:
    metadata:
      labels:
        app: bpechave
    spec:
      containers:
      - name: bpechave
        image: localhost:32000/bpe-chave:v1
        ports:
        - containerPort: 8080

