apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpeqrcode-deployment
  labels:
    app: bpeqrcode
spec:
  selector:
    matchLabels:
      app: bpeqrcode
  template:
    metadata:
      labels:
        app: bpeqrcode
    spec:
      containers:
        - name: bpeqrcode
          image: localhost:32000/bpe-qrcode:v1
          ports:
            - containerPort: 8080
