apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bpe-qrcode
    version: v11
  name: bpe-qrcode-v11
  namespace: bpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpe-qrcode
      version: v11
  template:
    metadata:
      labels:
        app: bpe-qrcode
        version: v11
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: bpe-qrcode
        image: 192.168.1.9:5000/bpe-qrcode:1.0.11
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTIONS
          value: -Xms15m -Xmx15m -Xmn15m
        - name: ambiente
          valueFrom:
            configMapKeyRef:
              name: bpe-config
              key: ambiente
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
        securityContext:
          privileged: false
      imagePullSecrets:
        - name: service-registry