apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bpe-api
    version: 1.0.9
  name: bpe-api-1.0.9
  namespace: bpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpe-api
      version: 1.0.9
  template:
    metadata:
      labels:
        app: bpe-api
        version: 1.0.9
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: bpe-api
        image: 192.168.1.103:5000/bpe-api:1.0.9
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTIONS
          value: -Xms15m -Xmx15m -Xmn15m
        - name: ambiente
          valueFrom:
            configMapKeyRef:
              name: bpe-config
              key: ambiente
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
        securityContext:
          privileged: false
      imagePullSecrets:
        - name: service-registry