apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bpe-api
spec:
  host: bpe-api
  subsets:
    - name: v2
      labels:
        version: 1.0.2
    - name: v3
      labels:
        version: 1.0.3


