apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bpe-qrcode
    version: 1.0.0
  name: bpe-qrcode-1.0.0
  namespace: bpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpe-qrcode
      version: 1.0.0
  template:
    metadata:
      labels:
        app: bpe-qrcode
        version: 1.0.0
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -Xms15m -Xmx15m -Xmn15m
          name: bpe-qrcode
          image: <local ip>:5000/bpe-qrcode:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: service-registry